### ISSUE TITLE
Feature request: Add search, delete, "insert after" functionality

### ISSUE THREAD

**Issue by philon123** [gammazero/deque#19]
In my use case I PushBack 99% of the time, but sometimes I wish to insert an element after a specific other one. O(n) performance would be fine. Search for and deleting an element would also be a fine addition. May I ask for these functions, pretty please? :)

**Comment by gammazero** [comment]
PR #21 has what you are looking for.  I will merge it if this is what you are looking for.

Instead of having an `InsertAfter` and `InsertBefore`, I have created an `Insert(at int, item interface{})` to insert the item at the specified index, which is the same as `InsertBefore`.  To insert something after the item at index `i`, c all `Insert(i+1, item)`.

I have also added an `Index` function to search for an item and return its index (position in deque), and a `Remove` that removed the item at the specified index.

**Comment by mrodriguez3313** [comment]
I actually just found this repo yesterday and started using it. Super awesome btw. And I came back to see if delete was implemented. Super glad it will soon be.

**Comment by gammazero** [comment]
@philon123
> before using Insert(at) it's basically always necessary to use Index(). So performance will be O(2n)

That assumes a use case where the position to insert at is not known and an item must be first searched for using `Index`.  Although that may be your use case, that is not necessarily the case.

In that use case, combining `Index` and `Insert` would not help because inserting requires bubbling the item being inserted from the front or back (whichever is shorter) to the destination.  Without first knowing the index there is no knowledge of which direction is shorter or if the item being searched for is even present. If not found the item being inserted would have been bubbled through the whole queue.

Lastly, if you are doing much inserting/removing in the middle of the queue, then a deque is probably the wrong data structure because it is strictly optimized for adding and removing items from the ends.

**Comment by gammazero** [comment]
It seems like the `Index`, `Insert`, and `Remove` may have some utility, although they should be the rare exception for a deque to be considered a reasonable data structure. That said, if you think this PR is still a good idea I will merge it.

**Comment by gammazero** [comment]
Would it give you what you want if I provide a function `RemoveFunc(f func(interface{}) bool)` that removes all items that satisfy `f(item)`?

**Comment by philon123** [comment]
@gammazero I think it would be a fine addition to the project of the PR was merged. The "search and remove" function also sounds like a good idea. It allows for more use cases without detriment to the core functionality. 

The only issue I can think of is users not noticing that they might be using bad performing functions. So the documentation should be clear about this. 

Thanks for spending time to discuss and help me and @mrodriguez3313 !

**Comment by mrodriguez3313** [comment]
I personally think I would just need delete. Bc for my use case I shouldn't allow for duplicates in the queue. But that does seem like a good feature in general to have available.

**Comment by gammazero** [comment]
After thinking about it, I think it is better to not provide the proposed `RemoveFunc`, as `Index` and `Remove` can alredy be used for this, and if the efficiency of this operation is a concern then a deque is not the best data structure.

**Comment by gammazero** [comment]
Addressed by #21
