### ISSUE TITLE
Ready for release?

### ISSUE THREAD

**Issue by rickb777** [gammazero/deque#28]
Deque is a good utility, clear and simple to use, and fast.

Is it ready for a release version? It's overdue for one, IMO :-)

Meanwhile, here are some ideas for methods that you could add:

 * push and insert slices - i.e. internalise the loop needed and reduce loop overhead
 * add adaptors for the PopBack, PopFront and At methods to provide iterators (Go 1.23)
 * add `Full() bool` method - a shortcut for `q.Len() == q.Cap()` which would be useful for anyone wanting to impose a maximum size or avoid resizing

**Comment by gammazero** [comment]
I have made a few changes that I think make it ready for release.

1. Added a `Grow` function that grows the deque's capacity, if necessary, to guarantee space for another n items.
This makes it unnecessary to add a `PushSlice` and `InsertSlize` since the main point of those, aside from some convenience, is to avoid possible multiple resizes when adding a number of items. With `Grow` the caller can do this:
```go
    q.Grow(len(elems))                                                                                                                                                                                                                                        
    for i := range elems {                                                                                                                                                                                                                                    
        q.PushBack(elems[i])                                                                                                                                                                                                                                  
    }                                                                                                                                                                                                                                                         
```
2. `New` now takes a single optional argument that specifies a base capacity. This allows the caller to specify the smallest capacity that Deque will resize down to, to avoid resizes. Previously `New` took two arguments, the initial capacity and the base capacity. With `Grow` the first argument is unecessary.
3. A `Swap` method has been added.
4. `Insert` now allows out-of-range indexes, resulting in adding an item to the front or back of the deque.
5. Replace `SetMinCapacity` with `SetBaseCapacity` that takes a minimum number of items to reserve space for.

I am considering an `Iter` function that returns a go1.23 iterator to iterate the items in the Deque, but doing that now will force callers to use go1.23. Callers can already do:
```go
for i := 0; i < q.Len(); i++ {
    doSomething(q.At(i))
}
```
This could also include `IterPopFront` and `IterPopBack`, but than may be somewhat unnecessary when the caller can already do:
```go
for q.Len() != 0 {
    process(q.Front())
    q.PopFront()
}
```
The iterator only saves one line of code:
```
for item := range IterPopFront() {
    process(item)
}
```
Might still be worth it to eliminate unnecessary range checks during iteration. WDYT?

As for a `Full` function, it seems like it might border on unnecessary syntactic sugar, at least for something that is not very common.  I think `if q.Len() == q.Cap()` is a bit more explicit. If a size limit is desired them it might be better wrap Deque in a type that checks if `Len` is at the limit when adding items. The wrapper's PushBask can then return a bool or error to indicate that the limit has been reached. WDYT?

**Comment by gammazero** [comment]
@rickb777 I think I will release v1.0.0 without PR #32 which requires go1.23. Later, when go1.24 is released I can merge the iterator PR and create release v1.1.0.

**Comment by gammazero** [comment]
Completed. Closing this PR as v1.0.0 is now released. Discussion continued in #35.
